#!/bin/bash

# Collect stdin to make sure nothing else reads/corrupts it.
cred_in=`cat`

# Check if the aws token is currently expired
PYENV_VERSION=genv aws sts get-caller-identity &> /dev/null
exit_status=$?

if [ $exit_status -ne 0 ]; then
  >&2 echo "Logging in, attempting to refresh token, warning this will fail, just run a 2nd time ;)"
  /usr/local/aws-cli/aws sso login --profile shared; aws2-wrap --profile shared --exec "aws-save-creds"
  exit_status=$?

  if [ $exit_status -ne 0 ]; then
    >&2 echo "Error logging in"
  fi
fi

docker-credential-ecr-login "$@" <<< "${cred_in}"
