#!/bin/bash
if docker-credential-ecr-login $@; then
  >&2 echo "Error Logging in, attempting to refresh token with aws-adfs login $?"
  PYENV_VERSION=genv username=${USER}@zefr.com password=`security find-generic-password -a ${USER} -s sso -w` aws-adfs login --env --adfs-host=sso.zefr.com --session-duration 43200

  >&2 echo "Trying again..."
fi
docker-credential-ecr-login $@
